apiVersion: v1
kind: Service
metadata:
  name: kube-starter-frontend
  namespace: kube-starter
  labels:
    app.kubernetes.io/name: kube-starter
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: kube-starter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kube-starter
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
