apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kube-starter-backend
  namespace: kube-starter
  labels:
    app.kubernetes.io/name: kube-starter
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kube-starter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-starter-backend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
